name: Internal Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  unit-test:
    name: Unit test on ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: -> Check the environment
      run: flutter doctor -v
    - name: -> Install dependencies
      run: flutter pub get
    - name: -> Analyze the source code
      run: flutter analyze
    - name: -> Check formatting
      run: flutter format --set-exit-if-changed --dry-run .
    # - name: -> Unit test
    #   run: flutter test
    # publish to pub.dev
    - name: -> Check before publish to pub.dev
      run: dart pub publish --dry-run
    - name: Setup credentials
      run: |
        cat <<EOF > $PUB_CACHE/credentials.json
        ${{ secrets.PUBDEV_CREDENTIAL }}
        EOF
    - name: -> Publish package
      run: dart pub publish -f